name = "JuliaVisualisation"
uuid = "d3e11a13-7335-4aa3-b8a4-de9f48a63ef1"
authors = ["tduretz <duretz@uni-frankfurt.de>"]
version = "0.1.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
FFMPEG = "c87230d0-a227-11e9-1b43-d7ebe4e7570a"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
GridGeometryUtils = "6f784e4f-3d6e-439e-b87e-1b67132dd330"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MakieTeX = "6d554a22-29e7-47bd-aee5-0c5f06619414"
MathTeXEngine = "0a4f8689-d25c-4efe-a92b-7142dfc1aa53"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
CairoMakie = "0.12.18"
GridGeometryUtils = "0.1.10"
MakieTeX = "0.4.3"
Polynomials = "4.0.21"
